require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
  RSpec:
    Patterns:
      - '_spec.rb$'

RSpec/MultipleDescribes:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/RedundantReturn:
  Enabled: false

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/ClassVars:
  Enabled: false

Documentation:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/StructInheritance:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false
